#pragma once
#include "config_common.h"

//图层数量
#define LAYER_STATE_8BIT

//usb
#define VENDOR_ID    0x4558 // "EX"
#define PRODUCT_ID   0xE605 // E6.5
#define DEVICE_VER   0x0001
#define MANUFACTURER Exclusive / E-Team
#define PRODUCT      MINI_PAD

/* key matrix size */
#define MATRIX_ROWS 5
#define MATRIX_COLS 4

/* key matrix pins */
#define MATRIX_ROW_PINS \
    { A1, A2, A3, A4, A5 }
#define MATRIX_COL_PINS \
    { A6, A7, B0, B1 }
#define UNUSED_PINS

/* COL2ROW or ROW2COL */
#define DIODE_DIRECTION ROW2COL

#define DRIVER_LED_TOTAL 17
#define RGBLED_NUM 17

#undef RGB_DI_PIN
#define RGB_DI_PIN B15
#define WS2812_SPI SPID2 
#define WS2812_SPI_MOSI_PIN B15
#define WS2812_SPI_MOSI_PAL_MODE 5 
#define WS2812_SPI_SCK_PIN B13 
#define WS2812_SPI_SCK_PAL_MODE 5 


//普通模式
#undef RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_ALPHAS_MODS		
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN	
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT	
#define ENABLE_RGB_MATRIX_BREATHING		
#define ENABLE_RGB_MATRIX_BAND_SAT		
#define ENABLE_RGB_MATRIX_BAND_VAL		
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT	
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL	
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT		
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL		
#define ENABLE_RGB_MATRIX_CYCLE_ALL		
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT		
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN		
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON	
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN	
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL	
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL	
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL	
#define ENABLE_RGB_MATRIX_DUAL_BEACON	
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON	
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS	
#define ENABLE_RGB_MATRIX_RAINDROPS	
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS	
#define ENABLE_RGB_MATRIX_HUE_BREATHING	
#define ENABLE_RGB_MATRIX_HUE_PENDULUM	
#define ENABLE_RGB_MATRIX_HUE_WAVE	
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL	
#define ENABLE_RGB_MATRIX_PIXEL_FLOW	
#define ENABLE_RGB_MATRIX_PIXEL_RAIN	
//??模式
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP	
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
//按键模式
#define RGB_MATRIX_KEYPRESSES
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS	
#define ENABLE_RGB_MATRIX_SPLASH	使RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH	
#define ENABLE_RGB_MATRIX_SOLID_SPLASH	
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#define DEBOUNCE 5