# MCU name
MCU = STM32F103

# Bootloader selection
BOOTLOADER = stm32duino


LTO_ENABLE = yes 
EXTRAKEY_ENABLE = yes 
ENCODER_ENABLE = no
NKRO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = spi

